glxgears / wglgears: avoid C99 "for" without explicit -std=
GCC < 5 defaults to -std=gnu89, failing to build:

glxgears.c: In function 'init':
glxgears.c:413: error: 'for' loop initial declaration used outside C99 mode

Fixes: 8c73555b4dd5 ("glxgears / wglgears: adjust colors for sRGB")
Reviewed-by: Erik Faye-Lund <erik.faye-lund@collabora.com>